// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVni7FbputDT5jA-McsJRHGudTNUa1HYU',
    appId: '1:299008599099:web:0dbba41ae13cd1fd9ca81e',
    messagingSenderId: '299008599099',
    projectId: 'quranik-ec616',
    authDomain: 'quranik-ec616.firebaseapp.com',
    databaseURL: 'https://quranik-ec616-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranik-ec616.appspot.com',
    measurementId: 'G-L3Y6X9RJZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6bf9gyraJ3IXUUfavLqDAvlNvQnI5y4',
    appId: '1:299008599099:android:891f37ab603db3f39ca81e',
    messagingSenderId: '299008599099',
    projectId: 'quranik-ec616',
    databaseURL: 'https://quranik-ec616-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranik-ec616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYUX3EbviPRWr0BwPTve0WqrD5tGy78k',
    appId: '1:299008599099:ios:15c4a15d3b5ddf3c9ca81e',
    messagingSenderId: '299008599099',
    projectId: 'quranik-ec616',
    databaseURL: 'https://quranik-ec616-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranik-ec616.appspot.com',
    iosClientId: '299008599099-46v0ft9bb9puoigu567dherggfsrh0gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasihAi',
  );
}
